#!/bin/bash
set -e

cd ~/.cache/

if [ -d "rwi/.git" ]; then
    git -C rwi pull
else
    git clone https://github.com/kiro-r/rwi.git
fi

cd ./rwi

mkdir -p ~/.config/hypr/custom/scripts

cp -r ./rwi.json ~/.config/
cp -r ./rwi.py ~/.config/hypr/custom/scripts/

sudo cp -r ./rwi /usr/bin/
sudo chmod +x /usr/bin/rwi

sudo cp -r ./rwi.service ~/.config/systemd/user/

systemctl --user daemon-reload
systemctl --user enable --now rwi.service

echo -e "\033[32mPlease edit ~/.config/rwi.json\033[0m"
echo -e "RWI installed"

cd ..
rm -rf ~/.cache/rwi